# `access` is used to set access controls on fields in root
# operation types (Query and Mutation).
# Remember to test this not through the localhost proxy
# that automatically sets the Apikey to be the admin key and bypasses these permissions,
# but use a separate GraphQL or API client to check these.
access:
  policies:
    - type: Query
      rules:
        - condition: true # access to named fields always allowed
          fields: [customer] # makes Query.customer public
