# This is a blanket way to make all Query endpoints public, i.e. not requiring an API Key or JWT.
# For example, you would typically do this for your product catalog queries.
# Remember to test this not through a GraphQL client that does not automatically set an api or admin key.
access:
  policies:
    - type: Query
      policyDefault:
        condition: true # allow all fields in Query with no authorization
