name: PR Checker
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

# cancel a previous check if running
# this avoids concurrent checks when multiple commits
# are pushed to a PR branch in a short time frame
# head_ref || ref_name ensures a value exists.
concurrency:
  group: cb-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  check-go-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
