deployment:
  identity:
    keys:
      - algorithm: HS256
        key: development-only
access:
  policies:
    - type: Query
      policyDefault:
        condition: false
      rules:
        - name: "jwt-control"
          fields: [me]
          condition: "?$jwt"
        - name: "introspection"
          fields: [__schema, __type]
          condition: true
configurationset:
  - configuration:
      name: postgresql_config
      uri: postgresql://postgresqlaws.introspection.stepzen.net/introspection?user=testUserIntrospection&password=HurricaneStartingSample1934
